apiVersion: ray.io/v1
kind: RayService
metadata:
  name: deepseek-r1
spec:
  serveConfigV2: |
    applications:
    - args:
        llm_configs:
          - model_loading_config:
              model_id: deepseek
              model_source: deepseek-ai/DeepSeek-R1
            accelerator_type: H100
            engine_kwargs:
              tensor_parallel_size: 8
              pipeline_parallel_size: 1
              gpu_memory_utilization: 0.92
              dtype: auto
              max_num_seqs: 40
              max_model_len: 16384
              enable_chunked_prefill: true
              enable_prefix_caching: true
              trust_remote_code: true
      import_path: ray-operator.config.samples.vllm.llm:model
      name: llm
      route_prefix: "/"
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        pip: ["vllm==0.6.1.post2"]
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.44.1.daca7b-py310-gpu
            resources:
              limits:
                cpu: "2"
                memory: "8Gi"
              requests:
                cpu: "2"
                memory: "8Gi"
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 0
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray-ml:2.44.1.daca7b-py310-gpu
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: hf_api_token
            resources:
              limits:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "2"
              requests:
                cpu: "8"
                memory: "20Gi"
                nvidia.com/gpu: "2"
          # Please add the following taints to the GPU node.
          tolerations:
            - key: "nvidia.com/gpu"
              operator: "Exists"
              effect: "NoSchedule"
